import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case en
    case fr
    case zhHans = "zh-Hans"
    case zhHant = "zh-Hant"
    case pa

    var id: String { rawValue }

    var nativeName: String {
        switch self {
        case .en: "English"
        case .fr: "Français"
        case .zhHans: "简体中文"
        case .zhHant: "繁體中文"
        case .pa: "ਪੰਜਾਬੀ"
        }
    }

    var label: String {
        switch self {
        case .en: "English"
        case .fr: "French"
        case .zhHans: "Simplified Chinese"
        case .zhHant: "Traditional Chinese"
        case .pa: "Punjabi"
        }
    }

    static func normalize(_ value: String?) -> AppLanguage {
        let raw = (value ?? "").replacingOccurrences(of: "_", with: "-").lowercased()
        if raw.hasPrefix("fr") { return .fr }
        if raw == "zh-tw" || raw == "zh-hk" || raw.contains("hant") { return .zhHant }
        if raw.hasPrefix("zh") { return .zhHans }
        if raw.hasPrefix("pa") || raw.hasPrefix("pan") { return .pa }
        return .en
    }
}

enum L10n {
    static func text(_ key: String, locale: String) -> String {
        let lang = AppLanguage.normalize(locale).rawValue
        return copy[lang]?[key] ?? copy["en"]?[key] ?? key
    }

    private static let copy: [String: [String: String]] = [
        "en": [
            "tab.browse": "Browse",
            "tab.myPosts": "My Posts",
            "tab.messages": "Messages",
            "tab.account": "Account",
            "staff.admin": "Admin",
            "staff.manage": "Manage",
            "account.title": "Account",
            "account.language": "Language",
            "account.languageHint": "Use this language for the app, emails, and alerts when available.",
            "account.appearance": "Appearance",
            "account.theme": "Theme",
            "account.profile": "Profile",
            "account.editName": "Edit display name",
            "account.verified": "Verified",
            "account.unverified": "Unverified",
            "account.signOut": "Sign out",
            "account.welcome": "Welcome to Total Free",
            "account.welcomeBody": "Browse freely without an account. Sign in to post, request, and get alerts.",
            "auth.verifyEmail": "Almost there — check your email to confirm your account, then sign in.",
            "browse.search": "Search free stuff",
            "browse.filters": "Filters",
            "browse.source": "Source",
            "browse.allSources": "All sources",
            "browse.category": "Category",
            "browse.allCategories": "All categories",
            "browse.clearFilters": "Clear filters",
            "browse.give": "Give away",
            "browse.request": "Request",
            "browse.freeItems": "Free items",
            "browse.list": "List",
            "browse.map": "Map",
            "browse.loading": "Finding free things...",
            "browse.emptyTitle": "Nothing here yet",
            "browse.emptyMessage": "Try a different search or filter. New free items appear as neighbours post them.",
            "listing.translate": "Translate",
            "listing.original": "Show original",
            "listing.translating": "Translating...",
            "listing.machine": "Machine translation. Original content is preserved.",
            "alerts.title": "Alerts",
            "alerts.done": "Done",
            "alerts.markAll": "Mark all read",
            "alerts.emptyTitle": "You're all caught up",
            "alerts.emptyMessage": "Alerts about your posts and requests show up here. Conversations live in Messages.",
            "alerts.detailTitle": "Alert",
            "alerts.delete": "Delete",
            "alerts.openReports": "Open safety reports",
            "alerts.openQueue": "Open moderation queue",
            "alerts.openBusiness": "Open business approvals",
            "alerts.openClaims": "Open organization claims",
            "alerts.viewListing": "View listing",
            "alerts.openConversation": "Open conversation",
            "notification.request_new": "New request on your post",
            "notification.request_update": "Request update",
            "notification.message_new": "New message",
            "notification.listing_approved": "Post approved",
            "notification.listing_rejected": "Post needs changes",
            "notification.sponsor_approved": "Business approved",
            "notification.match_found": "New match",
            "notification.admin_report_new": "Report needs review",
            "notification.admin_listing_pending": "Post pending review",
            "notification.admin_business_pending": "Business needs approval",
            "notification.admin_org_claim_pending": "Organization claim needs review",
        ],
        "fr": [
            "tab.browse": "Explorer",
            "tab.myPosts": "Mes annonces",
            "tab.messages": "Messages",
            "tab.account": "Compte",
            "staff.admin": "Admin",
            "staff.manage": "Gérer",
            "account.title": "Compte",
            "account.language": "Langue",
            "account.languageHint": "Utiliser cette langue pour l’app, les courriels et les alertes si disponible.",
            "account.appearance": "Apparence",
            "account.theme": "Thème",
            "account.profile": "Profil",
            "account.editName": "Modifier le nom affiché",
            "account.verified": "Vérifié",
            "account.unverified": "Non vérifié",
            "account.signOut": "Déconnexion",
            "account.welcome": "Bienvenue sur Total Free",
            "account.welcomeBody": "Vous pouvez explorer sans compte. Connectez-vous pour publier, demander et recevoir des alertes.",
            "auth.verifyEmail": "Presque terminé — confirmez votre courriel, puis connectez-vous.",
            "browse.search": "Rechercher du gratuit",
            "browse.filters": "Filtres",
            "browse.source": "Source",
            "browse.allSources": "Toutes les sources",
            "browse.category": "Catégorie",
            "browse.allCategories": "Toutes les catégories",
            "browse.clearFilters": "Effacer les filtres",
            "browse.give": "Donner",
            "browse.request": "Demander",
            "browse.freeItems": "Articles gratuits",
            "browse.list": "Liste",
            "browse.map": "Carte",
            "browse.loading": "Recherche de gratuit...",
            "browse.emptyTitle": "Rien pour le moment",
            "browse.emptyMessage": "Essayez une autre recherche ou un autre filtre.",
            "listing.translate": "Traduire",
            "listing.original": "Afficher l’original",
            "listing.translating": "Traduction...",
            "listing.machine": "Traduction automatique. Le contenu original est conservé.",
            "alerts.title": "Alertes",
            "alerts.done": "Terminé",
            "alerts.markAll": "Tout marquer comme lu",
            "alerts.emptyTitle": "Tout est à jour",
            "alerts.emptyMessage": "Les alertes sur vos annonces et demandes apparaissent ici. Les conversations sont dans Messages.",
            "alerts.detailTitle": "Alerte",
            "alerts.delete": "Supprimer",
            "alerts.openReports": "Ouvrir les signalements",
            "alerts.openQueue": "Ouvrir la file de modération",
            "alerts.openBusiness": "Ouvrir les approbations d'entreprise",
            "alerts.openClaims": "Ouvrir les demandes d'organisme",
            "alerts.viewListing": "Voir l'annonce",
            "alerts.openConversation": "Ouvrir la conversation",
            "notification.request_new": "Nouvelle demande sur votre annonce",
            "notification.request_update": "Mise à jour de la demande",
            "notification.message_new": "Nouveau message",
            "notification.listing_approved": "Annonce approuvée",
            "notification.listing_rejected": "Annonce à modifier",
            "notification.sponsor_approved": "Entreprise approuvée",
            "notification.match_found": "Nouveau résultat",
            "notification.admin_report_new": "Signalement à vérifier",
            "notification.admin_listing_pending": "Annonce en attente",
            "notification.admin_business_pending": "Entreprise à approuver",
            "notification.admin_org_claim_pending": "Demande d'organisme à vérifier",
        ],
        "zh-Hans": [
            "tab.browse": "浏览",
            "tab.myPosts": "我的发布",
            "tab.messages": "消息",
            "tab.account": "账户",
            "staff.admin": "管理",
            "staff.manage": "处理",
            "account.title": "账户",
            "account.language": "语言",
            "account.languageHint": "应用、邮件和提醒会优先使用此语言。",
            "account.appearance": "外观",
            "account.theme": "主题",
            "account.profile": "个人资料",
            "account.editName": "修改显示名称",
            "account.verified": "已验证",
            "account.unverified": "未验证",
            "account.signOut": "退出登录",
            "account.welcome": "欢迎使用 Total Free",
            "account.welcomeBody": "无需账户也可以浏览。登录后可以发布、请求和接收提醒。",
            "auth.verifyEmail": "还差一步，请先确认邮箱，然后再登录。",
            "browse.search": "搜索免费资源",
            "browse.filters": "筛选",
            "browse.source": "来源",
            "browse.allSources": "所有来源",
            "browse.category": "类别",
            "browse.allCategories": "所有类别",
            "browse.clearFilters": "清除筛选",
            "browse.give": "赠送",
            "browse.request": "请求",
            "browse.freeItems": "免费资源",
            "browse.list": "列表",
            "browse.map": "地图",
            "browse.loading": "正在寻找免费资源...",
            "browse.emptyTitle": "暂时没有",
            "browse.emptyMessage": "换一个搜索或筛选试试。",
            "listing.translate": "翻译",
            "listing.original": "显示原文",
            "listing.translating": "翻译中...",
            "listing.machine": "机器翻译。原始内容已保留。",
            "alerts.title": "提醒",
            "alerts.done": "完成",
            "alerts.markAll": "全部标为已读",
            "alerts.emptyTitle": "目前没有待处理提醒",
            "alerts.emptyMessage": "与你的发布和请求有关的提醒会显示在这里。聊天在消息里。",
            "alerts.detailTitle": "提醒",
            "alerts.delete": "删除",
            "alerts.openReports": "打开安全举报",
            "alerts.openQueue": "打开审核队列",
            "alerts.openBusiness": "打开商家审批",
            "alerts.openClaims": "打开机构认领",
            "alerts.viewListing": "查看帖子",
            "alerts.openConversation": "打开对话",
            "notification.request_new": "你的帖子有新请求",
            "notification.request_update": "请求更新",
            "notification.message_new": "新消息",
            "notification.listing_approved": "帖子已通过",
            "notification.listing_rejected": "帖子需要修改",
            "notification.sponsor_approved": "商家已通过",
            "notification.match_found": "新的匹配",
            "notification.admin_report_new": "有举报待审核",
            "notification.admin_listing_pending": "有帖子待审核",
            "notification.admin_business_pending": "有商家待批准",
            "notification.admin_org_claim_pending": "有机构认领待审核",
        ],
        "zh-Hant": [
            "tab.browse": "瀏覽",
            "tab.myPosts": "我的發布",
            "tab.messages": "訊息",
            "tab.account": "帳戶",
            "staff.admin": "管理",
            "staff.manage": "處理",
            "account.title": "帳戶",
            "account.language": "語言",
            "account.languageHint": "應用、郵件和提醒會優先使用此語言。",
            "account.appearance": "外觀",
            "account.theme": "主題",
            "account.profile": "個人資料",
            "account.editName": "修改顯示名稱",
            "account.verified": "已驗證",
            "account.unverified": "未驗證",
            "account.signOut": "登出",
            "account.welcome": "歡迎使用 Total Free",
            "account.welcomeBody": "無需帳戶也可以瀏覽。登入後可以發布、請求和接收提醒。",
            "auth.verifyEmail": "還差一步，請先確認電郵，然後再登入。",
            "browse.search": "搜尋免費資源",
            "browse.filters": "篩選",
            "browse.source": "來源",
            "browse.allSources": "所有來源",
            "browse.category": "類別",
            "browse.allCategories": "所有類別",
            "browse.clearFilters": "清除篩選",
            "browse.give": "贈送",
            "browse.request": "請求",
            "browse.freeItems": "免費資源",
            "browse.list": "列表",
            "browse.map": "地圖",
            "browse.loading": "正在尋找免費資源...",
            "browse.emptyTitle": "暫時沒有",
            "browse.emptyMessage": "換一個搜尋或篩選試試。",
            "listing.translate": "翻譯",
            "listing.original": "顯示原文",
            "listing.translating": "翻譯中...",
            "listing.machine": "機器翻譯。原始內容已保留。",
            "alerts.title": "提醒",
            "alerts.done": "完成",
            "alerts.markAll": "全部標為已讀",
            "alerts.emptyTitle": "目前沒有待處理提醒",
            "alerts.emptyMessage": "與你的發布和請求有關的提醒會顯示在這裡。聊天在訊息裡。",
            "alerts.detailTitle": "提醒",
            "alerts.delete": "刪除",
            "alerts.openReports": "打開安全舉報",
            "alerts.openQueue": "打開審核佇列",
            "alerts.openBusiness": "打開商家審批",
            "alerts.openClaims": "打開機構認領",
            "alerts.viewListing": "查看帖子",
            "alerts.openConversation": "打開對話",
            "notification.request_new": "你的帖子有新請求",
            "notification.request_update": "請求更新",
            "notification.message_new": "新訊息",
            "notification.listing_approved": "帖子已通過",
            "notification.listing_rejected": "帖子需要修改",
            "notification.sponsor_approved": "商家已通過",
            "notification.match_found": "新的匹配",
            "notification.admin_report_new": "有舉報待審核",
            "notification.admin_listing_pending": "有帖子待審核",
            "notification.admin_business_pending": "有商家待批准",
            "notification.admin_org_claim_pending": "有機構認領待審核",
        ],
        "pa": [
            "tab.browse": "ਵੇਖੋ",
            "tab.myPosts": "ਮੇਰੀਆਂ ਪੋਸਟਾਂ",
            "tab.messages": "ਸੁਨੇਹੇ",
            "tab.account": "ਖਾਤਾ",
            "staff.admin": "ਐਡਮਿਨ",
            "staff.manage": "ਸੰਭਾਲੋ",
            "account.title": "ਖਾਤਾ",
            "account.language": "ਭਾਸ਼ਾ",
            "account.languageHint": "ਐਪ, ਈਮੇਲ ਅਤੇ ਅਲਰਟ ਲਈ ਇਹ ਭਾਸ਼ਾ ਵਰਤੋ।",
            "account.appearance": "ਦਿੱਖ",
            "account.theme": "ਥੀਮ",
            "account.profile": "ਪ੍ਰੋਫ਼ਾਈਲ",
            "account.editName": "ਨਾਮ ਬਦਲੋ",
            "account.verified": "ਪੁਸ਼ਟੀ ਹੋਈ",
            "account.unverified": "ਪੁਸ਼ਟੀ ਨਹੀਂ",
            "account.signOut": "ਸਾਈਨ ਆਉਟ",
            "account.welcome": "Total Free ਵਿੱਚ ਸੁਆਗਤ ਹੈ",
            "account.welcomeBody": "ਬਿਨਾਂ ਖਾਤੇ ਵੇਖੋ। ਪੋਸਟ ਕਰਨ, ਬੇਨਤੀ ਕਰਨ ਅਤੇ ਅਲਰਟ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।",
            "auth.verifyEmail": "ਲਗਭਗ ਹੋ ਗਿਆ — ਈਮੇਲ ਪੁਸ਼ਟੀ ਕਰੋ, ਫਿਰ ਸਾਈਨ ਇਨ ਕਰੋ।",
            "browse.search": "ਮੁਫ਼ਤ ਚੀਜ਼ਾਂ ਖੋਜੋ",
            "browse.filters": "ਫਿਲਟਰ",
            "browse.source": "ਸਰੋਤ",
            "browse.allSources": "ਸਾਰੇ ਸਰੋਤ",
            "browse.category": "ਸ਼੍ਰੇਣੀ",
            "browse.allCategories": "ਸਾਰੀਆਂ ਸ਼੍ਰੇਣੀਆਂ",
            "browse.clearFilters": "ਫਿਲਟਰ ਸਾਫ਼ ਕਰੋ",
            "browse.give": "ਦੇਣਾ",
            "browse.request": "ਮੰਗੋ",
            "browse.freeItems": "ਮੁਫ਼ਤ ਚੀਜ਼ਾਂ",
            "browse.list": "ਲਿਸਟ",
            "browse.map": "ਨਕਸ਼ਾ",
            "browse.loading": "ਮੁਫ਼ਤ ਚੀਜ਼ਾਂ ਲੱਭ ਰਿਹਾ ਹੈ...",
            "browse.emptyTitle": "ਹਾਲੇ ਕੁਝ ਨਹੀਂ",
            "browse.emptyMessage": "ਹੋਰ ਖੋਜ ਜਾਂ ਫਿਲਟਰ ਅਜ਼ਮਾਓ।",
            "listing.translate": "ਅਨੁਵਾਦ",
            "listing.original": "ਮੂਲ ਵੇਖੋ",
            "listing.translating": "ਅਨੁਵਾਦ ਹੋ ਰਿਹਾ ਹੈ...",
            "listing.machine": "ਮਸ਼ੀਨੀ ਅਨੁਵਾਦ। ਮੂਲ ਸਮੱਗਰੀ ਸੰਭਾਲੀ ਗਈ ਹੈ।",
            "alerts.title": "ਅਲਰਟ",
            "alerts.done": "ਮੁਕੰਮਲ",
            "alerts.markAll": "ਸਭ ਪੜ੍ਹਿਆ ਮਾਰਕ ਕਰੋ",
            "alerts.emptyTitle": "ਸਭ ਠੀਕ ਹੈ",
            "alerts.emptyMessage": "ਤੁਹਾਡੀਆਂ ਪੋਸਟਾਂ ਅਤੇ ਬੇਨਤੀਆਂ ਦੇ ਅਲਰਟ ਇੱਥੇ ਆਉਣਗੇ। ਗੱਲਬਾਤ Messages ਵਿੱਚ ਹੈ।",
            "alerts.detailTitle": "ਅਲਰਟ",
            "alerts.delete": "ਮਿਟਾਓ",
            "alerts.openReports": "ਰਿਪੋਰਟਾਂ ਖੋਲ੍ਹੋ",
            "alerts.openQueue": "ਮੋਡਰੇਸ਼ਨ ਖੋਲ੍ਹੋ",
            "alerts.openBusiness": "ਕਾਰੋਬਾਰ ਮਨਜ਼ੂਰੀ ਖੋਲ੍ਹੋ",
            "alerts.openClaims": "ਸੰਗਠਨ ਕਲੇਮ ਖੋਲ੍ਹੋ",
            "alerts.viewListing": "ਪੋਸਟ ਵੇਖੋ",
            "alerts.openConversation": "ਗੱਲਬਾਤ ਖੋਲ੍ਹੋ",
            "notification.request_new": "ਤੁਹਾਡੀ ਪੋਸਟ ਤੇ ਨਵੀਂ ਬੇਨਤੀ",
            "notification.request_update": "ਬੇਨਤੀ ਅਪਡੇਟ",
            "notification.message_new": "ਨਵਾਂ ਸੁਨੇਹਾ",
            "notification.listing_approved": "ਪੋਸਟ ਮਨਜ਼ੂਰ",
            "notification.listing_rejected": "ਪੋਸਟ ਵਿੱਚ ਬਦਲਾਅ ਚਾਹੀਦੇ",
            "notification.sponsor_approved": "ਕਾਰੋਬਾਰ ਮਨਜ਼ੂਰ",
            "notification.match_found": "ਨਵਾਂ ਮੇਲ",
            "notification.admin_report_new": "ਰਿਪੋਰਟ ਸਮੀਖਿਆ ਲਈ",
            "notification.admin_listing_pending": "ਪੋਸਟ ਸਮੀਖਿਆ ਲਈ",
            "notification.admin_business_pending": "ਕਾਰੋਬਾਰ ਮਨਜ਼ੂਰੀ ਲਈ",
            "notification.admin_org_claim_pending": "ਸੰਗਠਨ ਕਲੇਮ ਸਮੀਖਿਆ ਲਈ",
        ],
    ]
}
